export const FETCH_BATMAN_START = "FETCH_BATMAN_START";
export const FETCH_BATMAN_SUCCESS = "FETCH_BATMAN_SUCCESS";
export const FETCH_BATMAN_SERIES_DESC_START = "FETCH_BATMAN_SERIES_DESC_START";
export const FETCH_BATMAN_SERIES_DESC_SUCCESS = "FETCH_BATMAN_SERIES_DESC_SUCCESS";
